[package]
name = "sortedsetkv"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "sortedsetkv"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
sled = "0.34.7"
log = "0.4"